# Example of verification of a Pytorch model with general VNNLIB specification.
#
# python abcrown.py --load_model models/cifar10_resnet/resnet2b.pth \
#                  --model resnet2b \
#                  --vnnlib_path ../../vnncomp2021/benchmarks/cifar2020/specs/cifar10/cifar10_spec_idx_0_eps_0.00784_n1.vnnlib \
#                  --input_shape -1 3 32 32
model:
  name: ACASXU  # This model is defined in model_defs.py. Add your own model definitions there.
  path: your_model.pth  # Path to PyTorch checkpoint.
   # vnnlib does not have input shape information, user should specify here
specification:
  # VNNLIB file specification.
  vnnlib_path: my_vnnlib.vnnlib
solver:
  batch_size: 2048  # Number of subdomains to compute in parallel in bound solver. Decrease if you run out of memory.
